# Generated by Django 4.2.8 on 2024-01-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_anouncement_post_category_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagepost',
            field=models.ImageField(default='defaultpost.jpg', upload_to='post_pics'),
        ),
    ]
