# Generated by Django 5.0 on 2023-12-13 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_anounc_post_category_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anounc',
        ),
        migrations.AddField(
            model_name='post',
            name='anouncement',
            field=models.TextField(max_length=150, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('O', 'Operator'), ('S', 'Science'), ('I', 'Internet'), ('OS', 'Operation System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
