# Generated by Django 5.0 on 2023-12-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
        ('blog', '0004_remove_post_anounc_post_anouncement_and_more'),
    ]

    operations = [
    ]
