# Generated by Django 4.2.8 on 2023-12-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20231225_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anouncement',
            field=models.TextField(max_length=1000, null=True, verbose_name='Аннотация'),
        ),
    ]
