# Generated by Django 4.2.8 on 2024-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_viewcount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite_taste',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite_taste',
            name='post_id_favorite',
        ),
        migrations.RemoveField(
            model_name='favorite_taste',
            name='user_id_favorite',
        ),
        migrations.AlterModelOptions(
            name='viewcount',
            options={'ordering': ('-view_data',)},
        ),
        migrations.RemoveIndex(
            model_name='viewcount',
            name='blog_viewco_viewed__0b448b_idx',
        ),
        migrations.RenameField(
            model_name='viewcount',
            old_name='viewed_on',
            new_name='view_data',
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['-view_data'], name='blog_viewco_view_da_6e3b6f_idx'),
        ),
        migrations.DeleteModel(
            name='Favorite_Taste',
        ),
    ]
