# Generated by Django 4.2.8 on 2023-12-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_anouncement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
