# Generated by Django 4.2.8 on 2024-01-11 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_favorite_taste_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagepost',
        ),
        migrations.AlterField(
            model_name='post',
            name='anouncement',
            field=models.TextField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=100000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
